### ISSUE TITLE
Great library but Blake2SP is very slow

### ISSUE THREAD

**Issue by BazzaCuda** [Xor-el/HashLib4Pascal#18]
As I've said elsewhere, HashLib4Pascal is great but I don't use it to generate hash codes because my desired hash, Blake2SP, is very slow.

I actually shell-out to run 7zip.exe in a command line, copy the output to the clipboard, and then examine the clipboard to get the Blake2SP hash code for any given file. This is *significantly* quicker than using HashLib4Pascal. This is a shame as the following code from my program could be reduced to a single statement if HashLib4Pascal could match the speed. It's not even close, unfortunately, particularly on large files of 1GB or more.

````
function Blake2sp(AFilePath: string): string;
  var
    vSL: TStringList;
    StartInfo: TStartupInfo;
    ProcInfo: TProcessInformation;
    CreateOK: boolean;
    cmd: string;
    params: string;
    posSpace: integer;
  begin
    result := '';
    FillChar(StartInfo, SizeOf(TStartupInfo), #0);
    FillChar(ProcInfo, SizeOf(TProcessInformation), #0);
    StartInfo.cb := SizeOf(TStartupInfo);
    StartInfo.wShowWindow := SW_HIDE;
    StartInfo.dwFlags := STARTF_USESHOWWINDOW;

    cmd := 'c:\windows\system32\cmd.exe';
    params := '/c B:\Tools\7-Zip\7z.exe h -scrcBLAKE2sp "' + AFilePath  + '" | clip';

    CreateOk := CreateProcess(PWideChar(cmd), PWideChar(params), nil, nil, FALSE,
      CREATE_NEW_PROCESS_GROUP + NORMAL_PRIORITY_CLASS, nil, StrScratchFolder, StartInfo, ProcInfo);

    case CreateOK of TRUE: WaitForSingleObject(ProcInfo.hProcess, INFINITE); end;

    vSL := TStringList.Create;
    try
      vSL.Text := Clipboard.AsText;
      case vSL.Count > 7 of TRUE: begin
        result := LowerCase(vSL[8]);
        posSpace := pos(' ', result);
        SetLength(result, posSpace - 1);
      end; end;
    finally
      vSL.Free;
    end;
  end;
````

If HashLib4Pascal/Blake2SP could be made lightning fast, as it is in 7zip, I would prefer to be using HashLib4Pascal.

Regards,
Baz.

**Comment by Xor-el** [comment]
@BazzaCuda ,  I would like to make a few clarifications on why your comparison is not a fair one.
1. HashLib4Pascal was written to provide a flexible and easy to use API for hashing. this comes at a performance cost due to it's strictly OOP nature.
2. the hash you specified, Blake2SP supports Parallel hashing. this is not enabled by default in HashLib for dependency reasons, however it is enabled by default in 7Zip. the parallel hashing gives the 7zip implementation a hugh performance boost compared to the version in HashLib.
3. you never stated the compiler you benchmarked with. I know for certain that FPC provides better performance than Delphi in this case.
4. the 7Zip implementation was written in ASM for performance reasons, HashLib was written in PurePascal for maintenance and compatibility reasons.

However, I agree with you that performance improvements can be made, unfortunately I don't have the time or zeal at the moment to do this as my attention has been caught up with other projects.
this been said, I am open to accepting pull requests that aims to improve the general performance of the library.

**Comment by BazzaCuda** [comment]
Hi, thanks for the prompt reply and the clarifications. If I can find some time, I'll have a look and see if I can spot any obvious performance improvements, and submit them for your approval.

**Comment by BazzaCuda** [comment]
I owe you a huge apology. After comparing your implementation of Blake2SP with RapidCRC's, I realized I wasn't compiling with your USE_DELPHI_PPL compiller option, so all the processing was sequential not concurrent. Now that my code is actually using DoParallelComputation, not surprisingly it runs a lot faster! It may be worth mentioning the compiler options on the front page on Github but, ultimately, the error is mine. Apologies again.

**Comment by Xor-el** [comment]
Glad you were able to figure this out, I intentionally didn't mention the parallel mode since I treat it as a beta implementation.
I still need to do some refactoring and improvements to it to consider at par with my C# implementation.
Sadly, This refactoring has been delayed by time constraints on my end.
